# Promises

> 1. 中文译为`约定`，它代表一个异步操作的最终完成或失败，以及该异步操作的结果值。
> 2. 如多个ajax等待发送，我们可以先执行逻辑，不关心结果处理，这种“承诺将来会执行”的对象在JavaScript中称为Promise对象

*Promise对象状态*:

1. pending (进行中)
2. resolved (已完成)
3. rejected (已失败)

## 创建Promise

```js
const myFirstPromise = new Promise((resolve, reject) => {
  // 做一些异步操作， 最终会调用以下两者之一
  // resolve(someValue)         fulfilled
  // reject('failure reason')   rejected
})

// 让函数拥有promise功能， 只需让其返回一个promise即可
function myAsyncFunction(url) {
  return new Promise((resolve, reject) => {
    //当异步代码执行成功时，我们才会调用resolve(...), 当异步代码失败时就会调用reject(...)
    const xhr = new XMLHttpRequest()
    xhr.open()
    xhr.onload = () => resolve(xhr.responseText)
    xhr.onerror = () => reject(xhr.statusText)
    xhr.send()
  })
}
```

## 使用

```js
function fun1() {
  return new Promise((resolve, reject) => {
    //在本例中，我们使用setTimeout(...)来模拟异步代码，实际编码时可能是XHR请求或是HTML5的一些API方法.
    console.log('方法一开始处理。。。')
    setTimeout(function () {
      resolve({
        name: '张三',
        age: 18
      })
    }, 2000)
  })
}

function fun2() {
  return new Promise((resolve, reject) => {
    console.log('方法二开始处理。。。')
    setTimeout(function () {
      reject('fun2处理失败') // 通常，一遇到异常抛出，promise链就会停下来，直接调用链式中的catch处理程序来继续当前执行
    }, 4000)
  })
}

function fun3() {
  return new Promise((resolve, reject) => {
    console.log('方法三开始处理。。。')
    setTimeout(function () {
      resolve('fun3处理完成')
    }, 4000)
  })
}

fun1()
  .then(function (data) {
    // data是上面fun1调用resolve(...)方法传入的值.
    console.log(data, 'fun1执行完成')
    return fun2()
  })
  .then(function (data) {
    console.log(data)
    return fun3()
  })
  .catch(function (error) {
    console.log(error)
  })
  .then(function (data) {
    console.log(data)
  })
```

## Catch 的后续链式操作

```js
new Promise((resolve, reject) => {
  console.log('Initial')
  resolve()
})
  .then(() => {
    throw new Error('Something failed')
    console.log('Do this')
  })
  .catch((e) => {
    console.log('Do that', e)
  })
  .then(() => {
    console.log('Do this whatever happened before')
  })
```

## 使用promises的优势

### 1.解决回调地狱（Callback Hell）问题

```js
//在过去，多多重的异步操作，会导致经典的回调地狱
doSomething(function(result) {
  .....
  doSomethingElse(result, function(newResult) {
    ....
    doThirdThing(newResult, function(finalResult) {
      console.log('Got the final result: ' + finalResult)
    }, failureCallback)
  }, failureCallback)
}, failureCallback)

// 新的功能方法，我们把回调绑定到被返回的Promis上代替以往的做法，形成一个promise链 执行代码和处理结果的代码清晰地分离
doSomething().then(function(result) {
  return doSomethingElse(result)
})
.then(function(newResult) {
  return doThirdThind(newResult)
})
.then(function(finalResult) {
  console.log('Got the final result: ' + finalResult)
})
.catch(failureCallback)
```

### 2.更好地进行错误捕获

```js
// 使用 setTimeout 模拟异步操作，在其中抛出了个异常。但由于异步回调中，回调函数的执行栈与原函数分离开，导致外部无法抓住异常。
function fetch(callback) {
  setTimeout(() => {
    throw Error('请求失败')
  }, 2000)
}

try {
  fetch(() => {
    console.log('请求处理') //不会执行
  })
} catch(e) {
  console.log('触发异常', e) //不会执行
}

// 程序崩溃
// Uncaught Error: 请求失败
```

```js
function fetch(callback) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject('请求失败')
    }， 2000)
  })
}

fetch()
.then(function(data) {
  console.log('请求处理')
  console.log(data)
}, function(reason, data) {
  console.log('触发失败')
  console.log(reason)
})
// 或者
fetch()
.then(function(data) {
  console.log('请求处理')
  console.log(data)
})
.catch(function(reason) {
  console.log(reason)
})
```

## 高级一点的例子

```js
'use strict'
let promiseCount = 0

function promiseDemo() {
  let thisPromiseCount = ++promiseCount

  let log = document.getElementById('log')
  log.insertAdjacentHTML('beforeend', `<br/><br/>第${thisPromiseCount}次点击: <br/><small>同步代码开始...</small><br/>`)

  // 新构建一个 Promise 实例：使用Promise实现每过一段时间给计数器加一的过程，每段时间间隔为1~3秒不等
  let p1 = new Promise((resolve, reject) => {
    let consume = Math.random() * 2000 + 1000
    log.insertAdjacentHTML('beforeend', '<small>Promise异步代码开始...</small><br/>')
    window.setTimeout(function () {
      resolve('Promise异步代码结束! 耗时:' + consume)
    }, consume)
  })

  // Promise不论成功或失败都会调用 then
  // catch() 只有当promise失败时调用
  p1.then(function (data) {
    log.insertAdjacentHTML('beforeend', '<small>' + data + '</small>')
  })
    .catch(function (reason) {
      console.log('处理失败的promise(' + reason + ')')
    })

  log.insertAdjacentHTML('beforeend', '<small>Promise made 同步代码结束</small><br/>')
}
```
